import = [
	"~/.config/alacritty/oxocabron.toml",
	# "~/.config/alacritty/oxocabron_light.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[font]
size = 14

[font.bold]
family = "Fisa Code"
style = "Bold"

[font.bold_italic]
family = "Fisa Code"
style = "Bold Italic"

[font.italic]
family = "Fisa Code"
style = "Regular Italic"

[font.normal]
family = "Fisa Code"
style = "Light"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Super|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[scrolling]
history = 5000

[shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 3
