[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4A4A4A"
blue = "#425C7B"
cyan = "#427B61"
green = "#5C7B42"
magenta = "#61427B"
red = "#7B425C"
white = "#D4D4D4"
yellow = "#7B6142"

[colors.normal]
black = "#2B2B2B"
blue = "#5E6873"
cyan = "#5E736A"
green = "#68735E"
magenta = "#6A5E73"
red = "#735E68"
white = "#C4C4C4"
yellow = "#736A5E"

[colors.primary]
background = "#333333"
foreground = "#B5B5B5"

[colors.search.focused_match]
background = "#756c5b"
foreground = "#363636"

[colors.search.matches]
background = "#a1a1a1"
foreground = "#363636"

[env]
TERM = "alacritty"

[font]
size = 14

[font.bold]
family = "Fisa Code"
style = "Bold"

[font.bold_italic]
family = "Fisa Code"
style = "Bold Italic"

[font.italic]
family = "Fisa Code"
style = "Regular Italic"

[font.normal]
family = "Fisa Code"
style = "Light"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Super|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[scrolling]
history = 5000

[shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 3
