[colors.primary]
foreground = "#C4C4C4"
background = "#333333"
[colors.normal]
black = "#2B2B2B"
red = "#735E68"
green = "#68735E"
yellow = "#736A5E"
blue = "#5E6873"
magenta = "#6A5E73"
cyan = "#5E736A"
white = "#D4D4D4"
[colors.bright]
black = "#424242"
red = "#7B425C"
green = "#5C7B42"
yellow = "#7B6142"
blue = "#425C7B"
magenta = "#61427B"
cyan = "#427B61"
white = "#CCCCCC"
[colors.dim]
black = "#2E2E2E"
red = "#4C3E44"
green = "#444C3E"
yellow = "#4C463E"
blue = "#3E444C"
magenta = "#463E4C"
cyan = "#3E4C46"
white = "#A8A8A8"
