[colors.primary]
foreground = "#3D3D3D"
background = "#EDEAD9"
[colors.normal]
black = "#FAF9F5"
red = "#B59BA7"
green = "#A7B59B"
yellow = "#B5AA9B"
blue = "#9BA7B5"
magenta = "#AA9BB5"
cyan = "#9BB5AA"
white = "#2B2B2B"
[colors.bright]
black = "#D5CDA4"
red = "#BD849E"
green = "#9EBD84"
yellow = "#BDA384"
blue = "#849EBD"
magenta = "#A384BD"
cyan = "#84BDA3"
white = "#303030"
[colors.dim]
black = "#F7F5EE"
red = "#7E5D6C"
green = "#6C7E5D"
yellow = "#7E6F5D"
blue = "#5D6C7E"
magenta = "#6F5D7E"
cyan = "#5D7E6F"
white = "#707070"
